name: Update prod branch on release
on:
  push:
  workflow_dispatch:
jobs:
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
    - run: |
        git branch
        git status