name: Merge Develop into Staging

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}

    - name: Merge Develop into Staging
      run: |
        git fetch
        git checkout staging
        git pull
        git merge origin/main -m "Auto-merge main to staging"
        git push origin staging
