name: Update prod branch on release
on:
  push:
  workflow_dispatch:
jobs:
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        token: ${{ github.TOKEN }}
        fetch-depth: 0
    - name: Merge Develop into Staging
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push