name: Update prod branch on release
on:
  push:
  workflow_dispatch:
jobs:
  updateBranch:
    name: Update staging branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        token: ${{ github.TOKEN }}
        fetch-depth: 0
    - name: Merge Develop into Staging
      run: |
        # git fetch
        # git checkout staging
        # git merge main -m "Auto-merge main into staging"
        # git push origin staging
        date > generated.txt
        git add .
        git commit -m "generated"
        git push