name: Merge Develop into Staging

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}

    - name: Merge Develop into Staging
      run: |
        git fetch
        git checkout staging
        git merge main
        git push staging
