name: Merge Develop into Staging

on:
  schedule:
    - cron: '40 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2

    - name: Merge Develop into Staging
      run: |
        git checkout -b staging
        git merge main
        git push origin staging
