name: Update Staging Branch

on:
  push:
    branches:
      - main

jobs:
  update_staging_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}

    - name: Checkout staging branch
      uses: actions/checkout@v2
      with:
        ref: staging
        fetch-depth: 0
        token: ${{ secrets.TOKEN }}

    - name: Rebase Staging Branch
      run: |
        git rebase main
        git push origin staging --force