name: Merge Develop into Staging

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

    - name: Merge Develop into Staging
      run: |
        git checkout -b staging
        git merge main
        git push origin staging
