# This is a basic workflow to help you get started with Actions

name: Nightly Staging Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{secrets.NIGHTLY_TOKEN}}

      - name: Run a multi-line script
        run: |
          git config user.name "Update branch"
          git config user.email github-actions@github.com
          git checkout staging
          git merge main
      - name: Push the updated staging branch
        run: git push origin staging